{-# LANGUAGE GADTs #-}
module Architecture.ARM.Pretty where

import Prelude hiding (EQ, LT, GT)

import Architecture.ARM.Common
import Architecture.ARM.Instructions.UAL

import Text.Printf
import Text.PrettyPrint

import Data.List

-- All this string building is inefficient. Fix it sometime using a real prettyprinting library

showRegister R0  = "R0"
showRegister R1  = "R1"
showRegister R2  = "R2"
showRegister R3  = "R3"
showRegister R4  = "R4"
showRegister R5  = "R5"
showRegister R6  = "R6"
showRegister R7  = "R7"
showRegister R8  = "R8"
showRegister R9  = "R9"
showRegister R10 = "SL"
showRegister R11 = "FP"
showRegister R12 = "IP"
showRegister SP  = "SP"
showRegister LR  = "LR"
showRegister PC  = "PC"

showArmShift S_LSL = "LSL"
showArmShift S_LSR = "LSR"
showArmShift S_ASR = "ASR"
showArmShift S_ROR = "ROR"

showCondition EQ = "EQ"
showCondition NE = "NE"
showCondition CS = "CS"
showCondition CC = "CC"
showCondition MI = "MI"
showCondition PL = "PL"
showCondition VS = "VS"
showCondition VC = "VC"
showCondition HI = "HI"
showCondition LS = "LS"
showCondition GE = "GE"
showCondition LT = "LT"
showCondition GT = "GT"
showCondition LE = "LE"
showCondition AL = ""
showCondition UND = "<unk>"


showArmOpData :: DataOp -> String
showArmOpData (Imm i) = printf "#%d" i
showArmOpData (Reg reg) = showRegister reg
showArmOpData (RegShiftImm sh i reg) = printf "%s, %s #%d" (showRegister reg) (showArmShift sh) i
showArmOpData (RegShiftReg sh regs reg) = printf "%s, %s %s" (showRegister reg) (showArmShift sh) (showRegister regs)
showArmOpData (RegShiftRRX reg) = printf "%s, RRX" (showRegister reg)

showArmOpMemory :: MemOp -> String
showArmOpMemory (MemReg base (Imm 0) up) = printf "[%s]" (showRegister base) ++ if up then "!" else ""
showArmOpMemory (MemReg base d up) = printf "[%s, %s]" (showRegister base) (showArmOpData d) ++ if up then "!" else ""
showArmOpMemory (MemRegNeg base d up) = printf "[%s, -%s]" (showRegister base) (showArmOpData d) ++ if up then "!" else ""
showArmOpMemory (MemRegPost base d) = printf "[%s], %s" (showRegister base) (showArmOpData d)
showArmOpMemory (MemRegPostNeg base d) = printf "[%s], -%s" (showRegister base) (showArmOpData d)


showArmOpMultiple :: MultiRegOp -> String
showArmOpMultiple (Regs rs) = "{" ++ (intercalate ", " . map showRegister $ rs) ++ "}"
showArmOpMultiple (RegsCaret rs) = "{" ++ (intercalate ", " . map showRegister $ rs) ++ "}^"

showInstruction :: Instruction UAL c -> String
showInstruction (B off)  = printf "B%%s 0x%x" off
showInstruction (BL off) = printf "BL%%s 0x%x" off
showInstruction (BLX rd) = printf "BLX%%s %s" (showRegister rd)
showInstruction (BX  rd) = printf "BX%%s %s"  (showRegister rd)
showInstruction (BXJ rd) = printf "BXJ%%s %s" (showRegister rd)
showInstruction (AND  rd rn k) = printf "AND%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (ANDS rd rn k) = printf "ANDS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (EOR  rd rn k) = printf "EOR%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (EORS rd rn k) = printf "EORS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (SUB  rd rn k) = printf "SUB%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (SUBS rd rn k) = printf "SUBS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (RSB  rd rn k) = printf "RSB%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (RSBS rd rn k) = printf "RSBS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (ADD  rd rn k) = printf "ADD%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (ADDS rd rn k) = printf "ADDS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (ADC  rd rn k) = printf "ADC%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (ADCS rd rn k) = printf "ADCS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (SBC  rd rn k) = printf "SBC%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (SBCS rd rn k) = printf "SBCS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (RSC  rd rn k) = printf "RSC%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (RSCS rd rn k) = printf "RSCS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (TST rn d)     = printf "TST%%s %s, %s" (showRegister rn) (showArmOpData d)
showInstruction (TEQ rn d)     = printf "TEQ%%s %s, %s" (showRegister rn) (showArmOpData d)
showInstruction (CMP rn d)     = printf "CMP%%s %s, %s" (showRegister rn) (showArmOpData d)
showInstruction (CMN rn d)     = printf "CMN%%s %s, %s" (showRegister rn) (showArmOpData d)
showInstruction (ORR  rd rn k) = printf "ORR%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (ORRS rd rn k) = printf "ORRS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData k)
showInstruction (MOV  rd d)    = printf "MOV%%s %s, %s"  (showRegister rd) (showArmOpData d)
showInstruction (MOVS rd d)    = printf "MOVS%%s %s, %s" (showRegister rd) (showArmOpData d)
showInstruction (LSL  rd d)    = printf "LSL%%s %s, %s"  (showRegister rd) (showArmOpData d)
showInstruction (LSLS rd d)    = printf "LSLS%%s %s, %s" (showRegister rd) (showArmOpData d)
showInstruction (LSR  rd d)    = printf "LSR%%s %s, %s"  (showRegister rd) (showArmOpData d)
showInstruction (LSRS rd d)    = printf "LSRS%%s %s, %s" (showRegister rd) (showArmOpData d)
showInstruction (ASR  rd d)    = printf "ASR%%s %s, %s"  (showRegister rd) (showArmOpData d)
showInstruction (ASRS rd d)    = printf "ASRS%%s %s, %s" (showRegister rd) (showArmOpData d)
showInstruction (RRX  rd rm)   = printf "RRX%%s %s, %s"  (showRegister rd) (showRegister rm)
showInstruction (RRXS rd rm)   = printf "RRXS%%s %s, %s" (showRegister rd) (showRegister rm)
showInstruction (ROR  rd d)    = printf "ROR%%s %s, %s"  (showRegister rd) (showArmOpData d)
showInstruction (RORS rd d)    = printf "RORS%%s %s, %s" (showRegister rd) (showArmOpData d)
showInstruction (BIC  rd rn d) = printf "BIC%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showArmOpData d)
showInstruction (BICS rd rn d) = printf "BICS%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData d)
showInstruction (MVN  rd d)    = printf "MVN%%s %s, %s"  (showRegister rd) (showArmOpData d)
showInstruction (MVNS rd d)    = printf "MVNS%%s %s, %s" (showRegister rd) (showArmOpData d)
showInstruction (MLA  rd rn rm ra)    = printf "MLA%%s %s, %s, %s, %s"     (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (MLAS rd rn rm ra)    = printf "MLAS%%s %s, %s, %s, %s"    (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (MUL  rd rn rm)       = printf "MUL%%s %s, %s, %s"     (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (MULS rd rn rm)       = printf "MULS%%s %s, %s, %s"     (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMLABB  rd rn rm ra) = printf "SMLABB%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLABT  rd rn rm ra) = printf "SMLABT%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLATB  rd rn rm ra) = printf "SMLATB%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLATT  rd rn rm ra) = printf "SMLATT%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLAWB  rd rn rm ra) = printf "SMLAWB%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLAWT  rd rn rm ra) = printf "SMLAWT%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLAD   rd rn rm ra) = printf "SMLAD%%s %s, %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLADX  rd rn rm ra) = printf "SMLADX%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLAL   rd rn rm ra) = printf "SMLAL%%s %s, %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLALS  rd rn rm ra) = printf "SMLALS%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLALBB rd rn rm ra) = printf "SMLALBB%%s %s, %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLALBT rd rn rm ra) = printf "SMLALBT%%s %s, %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLALTB rd rn rm ra) = printf "SMLALTB%%s %s, %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLALTT rd rn rm ra) = printf "SMLALTT%%s %s, %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLALD  rd rn rm ra) = printf "SMLALD%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLALDX rd rn rm ra) = printf "SMLALDX%%s %s, %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLSD   rd rn rm ra) = printf "SMLSD%%s %s, %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLSDX  rd rn rm ra) = printf "SMLSDX%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLSLD  rd rn rm ra) = printf "SMLSLD%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMLSLDX rd rn rm ra) = printf "SMLSLDX%%s %s, %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMMLA   rd rn rm ra) = printf "SMMLA%%s %s, %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMMLAR  rd rn rm ra) = printf "SMMLAR%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMMUL   rd rn rm)    = printf "SMMUL%%s %s, %s, %s"       (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMMULR  rd rn rm)    = printf "SMMULR%%s %s, %s, %s"      (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMMLS   rd rn rm ra) = printf "SMMLS%%s %s, %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMMLSR  rd rn rm ra) = printf "SMMLSR%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMUAD   rd rn rm)    = printf "SMUAD%%s %s, %s, %s"       (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMUADX  rd rn rm)    = printf "SMUADX%%s %s, %s, %s"      (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMULBB  rd rn rm)    = printf "SMULBB%%s %s, %s, %s"      (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMULBT  rd rn rm)    = printf "SMULBT%%s %s, %s, %s"      (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMULTB  rd rn rm)    = printf "SMULTB%%s %s, %s, %s"      (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMULTT  rd rn rm)    = printf "SMULTT%%s %s, %s, %s"      (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMULL   rd rn rm ra) = printf "SMULL%%s %s, %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMULLS  rd rn rm ra) = printf "SMULLS%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (SMULWB  rd rn rm)    = printf "SMULWB%%s %s, %s, %s"      (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMULWT  rd rn rm)    = printf "SMULWT%%s %s, %s, %s"      (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMUSD   rd rn rm)    = printf "SMUSD%%s %s, %s, %s"       (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SMUSDX  rd rn rm)    = printf "SMUSDX%%s %s, %s, %s"      (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (UMAAL   rd rn rm ra) = printf "UMAAL%%s %s, %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (UMLAL   rd rn rm ra) = printf "UMLAL%%s %s, %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (UMLALS  rd rn rm ra) = printf "UMLALS%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (UMULL   rd rn rm ra) = printf "UMULL%%s %s, %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (UMULLS  rd rn rm ra) = printf "UMULLS%%s %s, %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (QADD    rd rm rn) = printf "QADD%%s %s, %s, %s"    (showRegister rd) (showRegister rm) (showRegister rn) -- NB: inverted operands
showInstruction (QADD16  rd rn rm) = printf "QADD16%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (QADD8   rd rn rm) = printf "QADD8%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (QASX    rd rn rm) = printf "QASX%%s %s, %s, %s"    (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (QDADD   rd rn rm) = printf "QDADD%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (QDSUB   rd rn rm) = printf "QDSUB%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (QSUB    rd rm rn) = printf "QSUB%%s %s, %s, %s"    (showRegister rd) (showRegister rm) (showRegister rn) -- NB: inverted operands
showInstruction (QSUB16  rd rn rm) = printf "QSUB16%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (QSUB8   rd rn rm) = printf "QSUB8%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (QSAX    rd rn rm) = printf "QSAX%%s %s, %s, %s"    (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SADD16  rd rn rm) = printf "SADD16%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SADD8   rd rn rm) = printf "SADD8%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SASX    rd rn rm) = printf "SASX%%s %s, %s, %s"    (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SSUB16  rd rn rm) = printf "SSUB16%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SSUB8   rd rn rm) = printf "SSUB8%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SSAX    rd rn rm) = printf "SSAX%%s %s, %s, %s"    (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SHADD16 rd rn rm) = printf "SHADD16%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SHADD8  rd rn rm) = printf "SHADD8%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SHASX   rd rn rm) = printf "SHASX%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SHSUB16 rd rn rm) = printf "SHSUB16%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SHSUB8  rd rn rm) = printf "SHSUB8%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SHSAX   rd rn rm) = printf "SHSAX%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UADD16  rd rn rm) = printf "UADD16%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UADD8   rd rn rm) = printf "UADD8%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UASX    rd rn rm) = printf "UASX%%s %s, %s, %s"    (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (USUB16  rd rn rm) = printf "USUB16%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (USUB8   rd rn rm) = printf "USUB8%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (USAX    rd rn rm) = printf "USAX%%s %s, %s, %s"    (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UHADD16 rd rn rm) = printf "UHADD16%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UHADD8  rd rn rm) = printf "UHADD8%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UHASX   rd rn rm) = printf "UHASX%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UHSUB16 rd rn rm) = printf "UHSUB16%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UHSUB8  rd rn rm) = printf "UHSUB8%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UHSAX   rd rn rm) = printf "UHSAX%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UQADD16 rd rn rm) = printf "UQADD16%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UQADD8  rd rn rm) = printf "UQADD8%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UQASX   rd rn rm) = printf "UQASX%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UQSUB16 rd rn rm) = printf "UQSUB16%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UQSUB8  rd rn rm) = printf "UQSUB8%%s %s, %s, %s"  (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (UQSAX   rd rn rm) = printf "UQSAX%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showRegister rm) 
showInstruction (SXTAB16 rd rn d)  = printf "SXTAB16%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData d) 
showInstruction (SXTAB   rd rn d)  = printf "SXTAB%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showArmOpData d) 
showInstruction (SXTAH   rd rn d)  = printf "SXTAH%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showArmOpData d) 
showInstruction (SXTB16  rd d)     = printf "SXTB16%%s %s, %s"      (showRegister rd) (showArmOpData d)
showInstruction (SXTB    rd d)     = printf "SXTB%%s %s, %s"        (showRegister rd) (showArmOpData d)
showInstruction (SXTH    rd d)     = printf "SXTH%%s %s, %s"        (showRegister rd) (showArmOpData d)
showInstruction (UXTAB16 rd rn d)  = printf "UXTAB16%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData d)
showInstruction (UXTAB   rd rn d)  = printf "UXTAB%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showArmOpData d)
showInstruction (UXTAH   rd rn d)  = printf "UXTAH%%s %s, %s, %s"   (showRegister rd) (showRegister rn) (showArmOpData d)
showInstruction (UXTB16  rd d)     = printf "UXTB16%%s %s, %s"      (showRegister rd) (showArmOpData d)
showInstruction (UXTB    rd d)     = printf "UXTB%%s %s, %s"        (showRegister rd) (showArmOpData d)
showInstruction (UXTH    rd d)     = printf "UXTH%%s %s, %s"        (showRegister rd) (showArmOpData d)
showInstruction (UBFX    rd rn lsb w) = printf "UBFX%%s %s, %s, #%i, #%i" (showRegister rd) (showRegister rn) lsb w
showInstruction (SBFX    rd rn lsb w) = printf "SBFX%%s %s, %s, #%i, #%i" (showRegister rd) (showRegister rn) lsb w
showInstruction (CLZ rd rm) = printf "CLZ%%s %s, %s" (showRegister rd) (showRegister rm)
showInstruction (USAD8  rd rn rm) = printf "USAD8%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (USADA8 rd rn rm ra) = printf "USADA8%%s %s, %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (PKHBT rd rn d) = printf "PKHBT%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData d)
showInstruction (PKHTB rd rn d) = printf "PKHTB%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showArmOpData d)
showInstruction (REV   rd rm) = printf "REV%%s %s, %s" (showRegister rd) (showRegister rm)
showInstruction (REV16 rd rm) = printf "REV16%%s %s, %s" (showRegister rd) (showRegister rm)
showInstruction (REVSH rd rm) = printf "REVSH%%s %s, %s" (showRegister rd) (showRegister rm)
showInstruction (SEL rd rn rm) = printf "SEL%%s %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm)
showInstruction (SSAT   rd imm d)  = printf "SSAT%%s %s, #%i, %s"   (showRegister rd) imm (showArmOpData d)
showInstruction (SSAT16 rd imm rn) = printf "SSAT16%%s %s, #%i, %s" (showRegister rd) imm (showRegister rn)
showInstruction (USAT   rd imm d)  = printf "USAT%%s %s, #%i, %s"   (showRegister rd) imm (showArmOpData d)
showInstruction (USAT16 rd imm rn) = printf "USAT16%%s %s, #%i, %s" (showRegister rd) imm (showRegister rn)
showInstruction (MRS rd spec) = printf "MRS%%s %s, %s" (showRegister rd) (show spec) -- check
showInstruction (MSR x y d) = printf "MSR%%s" -- undefined -- FIX
showInstruction (LDR    rt mem) = printf "LDR%%s %s, %s"    (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRB   rt mem) = printf "LDRB%%s %s, %s"   (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRH   rt mem) = printf "LDRH%%s %s, %s"   (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRD   rt mem) = printf "LDRD%%s %s, %s"   (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRBT  rt mem) = printf "LDRBT%%s %s, %s"  (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRHT  rt mem) = printf "LDRHT%%s %s, %s"  (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRT   rt mem) = printf "LDRT%%s %s, %s"   (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRSB  rt mem) = printf "LDRSB%%s %s, %s"  (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRSBT rt mem) = printf "LDRSBT%%s %s, %s" (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRSH  rt mem) = printf "LDRSH%%s %s, %s"  (showRegister rt) (showArmOpMemory mem)
showInstruction (LDRSHT rt mem) = printf "LDRSHT%%s %s, %s" (showRegister rt) (showArmOpMemory mem)
showInstruction (STR    rt mem) = printf "STR%%s %s, %s"    (showRegister rt) (showArmOpMemory mem)
showInstruction (STRB   rt mem) = printf "STRB%%s %s, %s"   (showRegister rt) (showArmOpMemory mem)
showInstruction (STRH   rt mem) = printf "STRH%%s %s, %s"   (showRegister rt) (showArmOpMemory mem)
showInstruction (STRD   rt mem) = printf "STRD%%s %s, %s"   (showRegister rt) (showArmOpMemory mem)
showInstruction (STRBT  rt mem) = printf "STRBT%%s %s, %s"  (showRegister rt) (showArmOpMemory mem)
showInstruction (STRHT  rt mem) = printf "STRHT%%s %s, %s"  (showRegister rt) (showArmOpMemory mem)
showInstruction (STRT   rt mem) = printf "STRT%%s %s, %s"   (showRegister rt) (showArmOpMemory mem)
showInstruction (LDREX  rt mem) = printf "LDREX%%s %s, %s"  (showRegister rt) (showArmOpMemory mem)
showInstruction (LDREXB rt mem) = printf "LDREXB%%s %s, %s" (showRegister rt) (showArmOpMemory mem)
showInstruction (LDREXH rt mem) = printf "LDREXH%%s %s, %s" (showRegister rt) (showArmOpMemory mem)
showInstruction (LDREXD rt rt2 mem)    = printf "LDREXD%%s %s, %s, %s" (showRegister rt) (showRegister rt2) (showArmOpMemory mem)
showInstruction (STREX  rd rt mem)     = printf "STREX%%s %s, %s, %s"  (showRegister rd) (showRegister rt) (showArmOpMemory mem)
showInstruction (STREXB rd rt mem)     = printf "STREXB%%s %s, %s, %s" (showRegister rd) (showRegister rt) (showArmOpMemory mem)
showInstruction (STREXH rd rt mem)     = printf "STREXH%%s %s, %s, %s" (showRegister rd) (showRegister rt) (showArmOpMemory mem)
showInstruction (STREXD rd rt rt2 mem) = printf "STREXD%%s %s, %s, %s" (showRegister rd) (showRegister rt) (showRegister rt2) (showArmOpMemory mem)
showInstruction (LDM   bang rd regs)   = printf "LDM%%s %s%s, %s"   (showRegister rd) (cond "" "!" bang) (showArmOpMultiple regs)
showInstruction (LDMDA bang rd regs)   = printf "LDMDA%%s %s%s, %s" (showRegister rd) (cond "" "!" bang) (showArmOpMultiple regs)
showInstruction (LDMDB bang rd regs)   = printf "LDMDB%%s %s%s, %s" (showRegister rd) (cond "" "!" bang) (showArmOpMultiple regs)
showInstruction (LDMIB bang rd regs)   = printf "LDMIB%%s %s%s, %s" (showRegister rd) (cond "" "!" bang) (showArmOpMultiple regs)
showInstruction (STM   bang rd regs)   = printf "STM%%s %s%s, %s"   (showRegister rd) (cond "" "!" bang) (showArmOpMultiple regs)
showInstruction (STMDA bang rd regs)   = printf "STMDA%%s %s%s, %s" (showRegister rd) (cond "" "!" bang) (showArmOpMultiple regs)
showInstruction (STMDB bang rd regs)   = printf "STMDB%%s %s%s, %s" (showRegister rd) (cond "" "!" bang) (showArmOpMultiple regs)
showInstruction (STMIB bang rd regs)   = printf "STMIB%%s %s%s, %s" (showRegister rd) (cond "" "!" bang) (showArmOpMultiple regs)
showInstruction (PUSH regs) = printf "PUSH%%s %s" (showArmOpMultiple regs)
showInstruction (POP  regs) = printf "POP%%s %s"  (showArmOpMultiple regs)
showInstruction (SWP  rt rt2 rn) = printf "SWP%%s %s, %s, %s"  (showRegister rt) (showRegister rt2) (showArmOpMemory rn)
showInstruction (SWPB rt rt2 rn) = printf "SWPB%%s %s, %s, %s" (showRegister rt) (showRegister rt2) (showArmOpMemory rn)
showInstruction (SMC imm) = printf "SMC%%s 0x%x" imm
showInstruction (SVC imm) = printf "SVC%%s 0x%08x" imm
showInstruction (DBG imm) = printf "DBG%%s 0x%x" imm
showInstruction (DMB opt) = printf "DMB%%s %s" (show opt) -- FIX
showInstruction (DSB opt) = printf "DSB%%s %s" (show opt) -- FIX
showInstruction (ISB opt) = printf "ISB%%s %s" (show opt) -- FIX
showInstruction (PLI mem) = printf "PLI%%s %s" (showArmOpMemory mem)
showInstruction YIELD = printf "YIELD"
showInstruction WFE = printf "WFE"
showInstruction WFI = printf "WFI"
showInstruction SEV = printf "SEV"
showInstruction (BFC rd x) = printf "BFC%%s %s" (showRegister rd) "DUNNO YET" -- FIX
showInstruction (BFI rd rn x) = printf "BFI%%s" (showRegister rd) (showRegister rn) "DUNNO YET" -- FIX
showInstruction (MLS rd rn rm ra) = printf "MLS%%s %s, %s, %s, %s" (showRegister rd) (showRegister rn) (showRegister rm) (showRegister ra)
showInstruction (MOVW rd imm) = printf "MOVW%%s %s, #%i" (showRegister rd) imm
showInstruction (MOVT rd imm) = printf "MOVT%%s %s, #%i" (showRegister rd) imm
showInstruction (RBIT rd rm) = "rbit%s" -- undefined -- FIX

showInstruction (CPS imm32) = printf "CPS 0x%x" imm32
showInstruction (CPSIE a i f mode) = printf "CPSIE" -- FIX
showInstruction (CPSID a i f mode) = printf "CPSIE" -- FIX
showInstruction (SETEND end) = printf "SETEND %s" (show end) -- FIX
showInstruction (RFE   b r) = printf "RFE"   -- FIX
showInstruction (RFEDA b r) = printf "RFEDA" -- FIX
showInstruction (RFEDB b r) = printf "RFEDB" -- FIX
showInstruction (RFEIB b r) = printf "RFEIB" -- FIX
showInstruction (BKPT imm8) = printf "BKPT 0x%x" imm8
showInstruction (PLD mem) = "PLD" -- FIX
showInstruction (SRS   b r imm32) = "SRS" -- FIX
showInstruction (SRSDA b r imm32) = "SRSDA" -- FIX
showInstruction (SRSDB b r imm32) = "SRSDB" -- FIX
showInstruction (SRSIB b r imm32) = "SRSIB" -- FIX
showInstruction CLREX = "CLREX"
showInstruction (BLXUC imm32) = printf "BLX 0x%x" imm32

showGeneralInstruction :: GeneralInstruction UAL -> String
showGeneralInstruction Undefined = "UNDEFINED INSTRUCTION"
showGeneralInstruction (Unconditional x) = showInstruction x
showGeneralInstruction (Conditional cond x) = printf (showInstruction x) (showCondition cond)