{-# LANGUAGE TypeFamilies, GADTs #-}
module Architecture.ARM.Instructions.NEON where

import Architecture.ARM.Common

data NEON = NEON


instance InstructionSet NEON where
  data Instruction NEON c where
    VABA     :: Instruction NEON Conditional
    VABAL    :: Instruction NEON Conditional
    VABD     :: Instruction NEON Conditional
    VABDL    :: Instruction NEON Conditional
    VABS     :: Instruction NEON Conditional
    VACGE    :: Instruction NEON Conditional
    VACGT    :: Instruction NEON Conditional
    VADD     :: Instruction NEON Conditional
    VADDHN   :: Instruction NEON Conditional
    VADDL    :: Instruction NEON Conditional
    VADDW    :: Instruction NEON Conditional
    VAND     :: Instruction NEON Conditional
    VBIC     :: Instruction NEON Conditional
    VBIF     :: Instruction NEON Conditional
    VBIT     :: Instruction NEON Conditional
    VBSL     :: Instruction NEON Conditional
    VCEQ     :: Instruction NEON Conditional
    VCGE     :: Instruction NEON Conditional
    VCGT     :: Instruction NEON Conditional
    VCLE     :: Instruction NEON Conditional
    VCLS     :: Instruction NEON Conditional
    VCLT     :: Instruction NEON Conditional
    VCLZ     :: Instruction NEON Conditional
    VCNT     :: Instruction NEON Conditional
    VCVT     :: Instruction NEON Conditional
    VDUP     :: Instruction NEON Conditional
    VEOR     :: Instruction NEON Conditional
    VEXT     :: Instruction NEON Conditional
    VFMA     :: Instruction NEON Conditional
    VFMS     :: Instruction NEON Conditional
    VHADD    :: Instruction NEON Conditional
    VHSUB    :: Instruction NEON Conditional
    VLD1     :: Instruction NEON Conditional
    VLD2     :: Instruction NEON Conditional
    VLD3     :: Instruction NEON Conditional
    VLD4     :: Instruction NEON Conditional
    VMAX     :: Instruction NEON Conditional
    VMIN     :: Instruction NEON Conditional
    VMLA     :: Instruction NEON Conditional
    VMLAL    :: Instruction NEON Conditional
    VMLS     :: Instruction NEON Conditional
    VMLSL    :: Instruction NEON Conditional
    VMOV     :: Instruction NEON Conditional
    VMOVL    :: Instruction NEON Conditional
    VMOVN    :: Instruction NEON Conditional
    VMUL     :: Instruction NEON Conditional
    VMULL    :: Instruction NEON Conditional
    VMVN     :: Instruction NEON Conditional
    VNEG     :: Instruction NEON Conditional
    VORN     :: Instruction NEON Conditional
    VORR     :: Instruction NEON Conditional
    VPADAL   :: Instruction NEON Conditional
    VPADD    :: Instruction NEON Conditional
    VPADDL   :: Instruction NEON Conditional
    VPMAX    :: Instruction NEON Conditional
    VPMIN    :: Instruction NEON Conditional
    VQABS    :: Instruction NEON Conditional
    VQADD    :: Instruction NEON Conditional
    VQDMLAL  :: Instruction NEON Conditional
    VQDMLSL  :: Instruction NEON Conditional
    VQDMULH  :: Instruction NEON Conditional
    VQDMULL  :: Instruction NEON Conditional
    VQMOVN   :: Instruction NEON Conditional
    VQMOVUN  :: Instruction NEON Conditional
    VQNEG    :: Instruction NEON Conditional
    VQRDMULH :: Instruction NEON Conditional
    VQRSHL   :: Instruction NEON Conditional
    VQRSHRN  :: Instruction NEON Conditional
    VQRSHRUN :: Instruction NEON Conditional
    VQSHL    :: Instruction NEON Conditional
    VQSHLU   :: Instruction NEON Conditional
    VQSHRN   :: Instruction NEON Conditional
    VQSHRUN  :: Instruction NEON Conditional
    VQSUB    :: Instruction NEON Conditional
    VRADDHN  :: Instruction NEON Conditional
    VRECPE   :: Instruction NEON Conditional
    VRECPS   :: Instruction NEON Conditional
    VREV16   :: Instruction NEON Conditional
    VREV32   :: Instruction NEON Conditional
    VREV64   :: Instruction NEON Conditional
    VRHADD   :: Instruction NEON Conditional
    VRSHL    :: Instruction NEON Conditional
    VRSHR    :: Instruction NEON Conditional
    VRSHRN   :: Instruction NEON Conditional
    VRSQRTE  :: Instruction NEON Conditional
    VRSQRTS  :: Instruction NEON Conditional
    VRSRA    :: Instruction NEON Conditional
    VRSUBHN  :: Instruction NEON Conditional
    VSHL     :: Instruction NEON Conditional
    VSHLL    :: Instruction NEON Conditional
    VSHR     :: Instruction NEON Conditional
    VSHRN    :: Instruction NEON Conditional
    VSLI     :: Instruction NEON Conditional
    VSRA     :: Instruction NEON Conditional
    VSRI     :: Instruction NEON Conditional
    VST1     :: Instruction NEON Conditional
    VST2     :: Instruction NEON Conditional
    VST3     :: Instruction NEON Conditional
    VST4     :: Instruction NEON Conditional
    VSUB     :: Instruction NEON Conditional
    VSUBHN   :: Instruction NEON Conditional
    VSUBL    :: Instruction NEON Conditional
    VSUBW    :: Instruction NEON Conditional
    VSWP     :: Instruction NEON Conditional
    VTBL     :: Instruction NEON Conditional
    VTBX     :: Instruction NEON Conditional
    VTRN     :: Instruction NEON Conditional
    VTST     :: Instruction NEON Conditional
    VUZP     :: Instruction NEON Conditional
    VZIP     :: Instruction NEON Conditional

